# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38fa90578f19cf4c0ffbf7e458b41ece0c2f193433b3443b467cd53f6bb70d2531cd87e8edb3eed7b4b56727cce35363ae78f2db72aef3052578d54f657b2ee1

test:
  secret_key_base: f39f0e9b98ed1a02aad632d9f669db764aa6446e704b679531b07ce6966cbaf87f8aeda23727f716056a61b1bbf914d6266873dead7592818b485bdecc70481a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
